services:
  - type: web
    name: laravel-jobboard
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
